language: go
env:
  GO111MODULE=on
deploy:
  provider: heroku
  api_key:
    secure: "o5nFSnQygO3jSa41xQLfC9RsdoczE8X4D4hyy0mvIbdaqHyNMHsYvK88rIvle4bMq2om4Phr+noe1tkSnIOFMgnF7wYTUGn8sjKHYNmVmhBbq9BggikWmJKs9/fx1dRd+v7g4I4No8a9Uhr9zx2EIn+NU9CwsYCI08AIaYq+1vTMur89IxR/9G7xiB20Ruvf1Eil/ELCNEjygbwI72xZrRdHgQxIkHkCmsULleQt5/btd2TP3bXT6tL4zfU2hYambcPHywTwcDuFQL2PNxI9XMQZHCfaUXcNr5edXuI38oyIwrWVk+bXZ5XFevKVVEL7geJ2mg3GZzJVJj3Rmu6wOs/grml6Pg6KMkwcklGKc1M4Mzx25THmoLY/HqvZCkaXQlJzVpuXKqKGKb2s0EHYZ551j2faKYTfzXi3hGyxsCb4LfgJFVwqs+Hb1Zt1JDyyenQfZTx/Idw6XiDGE9MY5HOTCmq3F+bp4mj7UswY5v3TQBbWB/WV3u6Tnqf++ZW55dQH+pfQpO2Idk7M3ur64QQHyK/jRrMJa1aMyCn9bRcxZSoGpLVL68RD/inPiAh8f5G22MvYvGbzv8wb11gRLAFeGut+KHpUREPDup5zzAM7NnVD+qqkMLe8NmHe40ZlHxqX//Q0c/vfZfVR6XQ6zM8TU2N2MAyP1Etv/ypGeSM="
  app:
    ci-cd: pokemon-api-isaacsnk