language: go
env:
  GO111MODULE=on
deploy:
  provider: heroku
  api_key:
    secure: "emw5IX7h+3GG4FlITj4k9D1zde99VOxRIMZk9Puu/dpwSgDxCrODE2ZwCZ47T4K/OVNZUpo/SCvuHClmgM3wGRGMruA1aihQgRR/zDxPYfFnJjPNusNyaJpedmcCw12J4njKTS7ZfZKtpei8ClfYugUOLVwQOc1xd9QLfIqjzAlLEY8UKfOCDEqX2dunoPtOtvU/OD0wrqbAP4UiS9fx55SpcCpD9YFvAFH/c6Vn2gTCCyfFB+kIUmJv8P/PydCtE5U29pV46pq84TSETL4lM5f17I5PdBoqwLNviwaXPSmYLjbKkjC0uqLD92LFqEG85GKderpkIyRRDmgVJyAj7kWPISoglZD8/kbZYRkXBKawEOPnLNjZKF5zt2xk/02kCdVjWjFssc5geAMP7LnXNm3Zp8VkWnjyOQLpy2j9W4fGL9n3KHY0gIsq4cEDVh3wJN6hZjzLEwobq+RY4nGUt3eEySQCo6gpDDy/JbFWefRmibnOOtVsFBaUvuypj4CHyBRtZD0DRs8eVBCYhpprYtgpmiW+7jt0kB89CV7fVKRDzA90VVD/66nriPC7xMOoGE3BBMfM3w7fNZUlLSSA5FSSoxve07kvQgbVnVAMgm4jME3V3tpD9HzO4zr+FxcvY4JHcimmerUFYBX8XTGP0Ar10UTX3gFeJCb/a44iKcE="
  app:
    ci-cd: pokemon-api-isaacsnk