language: go
env:
  GO111MODULE=on
deploy:
  provider: heroku
  api_key:
    secure: "MOQ6c14t3k1yKgIjo6jLNp0D86GtKX7b+89cYfA+WTP0Z4XSttxpY/XemtZmpqZEwg+vFFQ15I0QJpe3dEnojExxpgy3QTdbHEkppqp/b65mALybzIfdibgHa+eAkf2HXG5WlTY1D2jmmetB+ib0CqUbEPY2kKJoMSdueAS4LSybjKnNx1XOuqcCQr2nrwhX1s0gjD2gzF8J79JeAucLQ5AgRPMCQVmOs+3dFPuVDspjTval1PQirI+HQVZ0lGIW+9wZPCvOlH2heZpO5Z5h/Ev3SbMVrjURILV+xi/T43A0qY+veqz6gqcahIGHCeHDV4/o67Fj+5rXE3CidMbAZS6TDMdxaPIa/9mnjqoyohib29IWVkJbtMMvh2DhfNqxohmphqEW5+mIkhtrgiK2sixGaf374y1w5APj0g4du2s4Z2fhNCx3rn+7EOlo02lX/wjfgD/2wAgDxDst9jma0gJFwrjsPZjPoODQUQ7dPCOJgnlPRXkWQuZH3GH9B+RoThuX8wpbuvaHntX7ppfud8b/rMog6oEx0UEZYt1ZaMYNNr/lQcL7JbxFlO6SOGHBtxV9oE7JakFU3aeHZb4yN8qUd+1Yr2ujsOreX/BxdJTnUkhXjSH2h339fC5LYwxxqM9IJSUaTR7ENZpkJM8ojzF7mrBPdna5aP4GKoTkFU4="
  app:
    ci-cd: pokemon-api-isaacsnk