language: go
env:
  GO111MODULE=on
deploy:
  provider: heroku
  api_key:
    secure: "kKtvIS/RvVskqsohIuuju5Orn8Zu2W82cRw7+BPciZSZZMez/LsgCtCRqJZS5bhkPzVbtWObColKefgkKFxjnVXQ9OOwhT00CAxtm1uIX5u+vaAT6ZtYVfo8MZqDxj/93pmu6u/o8tQsJZ/tQwY8t2fVrn7lFbAvGXU4Sh7BeSuVb9AGyLblC1HqyPKorbW5sbnhfVoBUorNwcvnrqgAAQS9cj7rR9UZZnmSf9iJ1CEDl7XbcEncrYroUAXJ467TWG8A1kmny55mB3F9Ta5O6OW1zbJX29dDL8I1+thmvzend7iypmnBNVbg8auc6Voei7vp0kmLZNHWKIhTOQJA5A6MI1Q5cg10RgL4Zeam6nr3GQwuSB5l0oJeHrMIbfen5ZyS8BjR80k3f6EVSD0VnosSwgebN4SV4OtK4kc1iE/1e0/WxdRsPHl0eECVWpQQ95V+1LOy3ipLVR+2EoAsAZW0Y14FV0skm+COC306VNJiHpsJZ74ZrYYr55cgqhGOgEAES7//mK6wbgJUbDuDc/r/R89nHuQyBfc7LKRX0guXrl7QsDhVxC2ynrgOkrAprqT/hJ5PzXMSkbEeGW7+NyCWyYywhxgCG2n+l+C5hD7k82+Sc7MLK2Sr3kxGYjdj3CVXtF9rX3pQsoAJuoq4z1ALuzzDmGHkOpKU1TuSHlw="
  app:
    ci-cd: pokemon-api-isaacsnk